# -*- coding: utf-8 -*-
"""Notion Style Blog

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13yD9_fkj88BEsVUXcTWMxUw4g5eOK3Di
"""

"""
HOW TO RUN THIS APP:
1. Open your terminal or command prompt.
2. Install the required libraries:
   pip install streamlit pandas Pillow
3. Run the application:
   streamlit run app.py
"""
import sys

# --- Dependency Check ---
try:
    import streamlit as st
    import pandas as pd
    from PIL import Image
except ImportError as e:
    print("\n" + "="*60)
    print(f"❌ CRITICAL ERROR: The library '{e.name}' is not installed.")
    print("="*60)
    print("To fix this, please run the following command in your terminal:\n")
    print("    pip install streamlit pandas Pillow")
    print("\n" + "="*60 + "\n")
    # Re-raise the error to stop execution
    raise

import sqlite3
import hashlib
from datetime import datetime
import io
import base64

# --- 配置页面 ---
st.set_page_config(
    page_title="My Digital Garden",
    page_icon="🌿",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- 样式设计 (Notion Dark Mode) ---
def local_css():
    st.markdown("""
    <style>
        /* 全局背景色 - 深邃黑 */
        .stApp {
            background-color: #191919;
            color: #FFFFFF;
        }

        /* 侧边栏背景 */
        [data-testid="stSidebar"] {
            background-color: #202020;
            border-right: 1px solid #2F2F2F;
        }

        /* 标题样式 */
        h1, h2, h3, h4, h5, h6 {
            font-family: 'Segoe UI', sans-serif;
            color: #FFFFFF !important;
            font-weight: 600;
        }

        /* 输入框样式 */
        .stTextInput > div > div > input, .stTextArea > div > div > textarea {
            background-color: #2F2F2F;
            color: #FFFFFF;
            border: 1px solid #3F3F3F;
            border-radius: 5px;
        }

        /* 按钮样式 */
        .stButton > button {
            background-color: #2F2F2F;
            color: white;
            border: 1px solid #3F3F3F;
            border-radius: 4px;
            transition: all 0.3s;
        }
        .stButton > button:hover {
            background-color: #3F3F3F;
            border-color: #5F5F5F;
        }

        /* 卡片容器样式 (模仿Notion Block) */
        .notion-card {
            background-color: #202020;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 15px;
            border: 1px solid #2F2F2F;
            transition: transform 0.2s;
        }
        .notion-card:hover {
            border-color: #4F4F4F;
        }

        /* 评论区样式 */
        .comment-box {
            background-color: #262626;
            padding: 10px;
            border-radius: 5px;
            margin-top: 5px;
            font-size: 0.9em;
            border-left: 3px solid #505050;
        }

        /* 去除Streamlit默认的Header和Footer */
        header {visibility: hidden;}
        footer {visibility: hidden;}

    </style>
    """, unsafe_allow_html=True)

local_css()

# --- 数据库管理 (SQLite) ---
DB_FILE = 'blog_data.db'

def init_db():
    conn = sqlite3.connect(DB_FILE)
    c = conn.cursor()

    # 用户表
    c.execute('''CREATE TABLE IF NOT EXISTS users (
                    username TEXT PRIMARY KEY,
                    password TEXT,
                    nickname TEXT,
                    avatar BLOB,
                    role TEXT,
                    is_active INTEGER
                )''')

    # 文章/作品表
    c.execute('''CREATE TABLE IF NOT EXISTS posts (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    category TEXT,
                    title TEXT,
                    content TEXT,
                    image BLOB,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )''')

    # 评论表
    c.execute('''CREATE TABLE IF NOT EXISTS comments (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    post_id INTEGER,
                    username TEXT,
                    content TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY(post_id) REFERENCES posts(id),
                    FOREIGN KEY(username) REFERENCES users(username)
                )''')

    # 创建默认管理员 (如果不存在)
    c.execute("SELECT * FROM users WHERE username = 'admin'")
    if not c.fetchone():
        pwd_hash = hashlib.sha256("admin123".encode()).hexdigest()
        c.execute("INSERT INTO users (username, password, nickname, role, is_active) VALUES (?, ?, ?, ?, ?)",
                  ('admin', pwd_hash, 'Admin', 'admin', 1))

    conn.commit()
    conn.close()

init_db()

# --- 辅助函数 ---
def make_hash(password):
    return hashlib.sha256(password.encode()).hexdigest()

def check_hashes(password, hashed_text):
    if make_hash(password) == hashed_text:
        return True
    return False

def get_avatar(username):
    conn = sqlite3.connect(DB_FILE)
    c = conn.cursor()
    c.execute("SELECT avatar FROM users WHERE username=?", (username,))
    data = c.fetchone()
    conn.close()
    if data and data[0]:
        return data[0]
    return None

def save_image_to_bytes(uploaded_file):
    if uploaded_file is None:
        return None
    bytes_data = uploaded_file.getvalue()
    return bytes_data

# --- 侧边栏：用户系统 ---
def sidebar_user_system():
    st.sidebar.title("🔐 Account")

    if 'logged_in' not in st.session_state:
        st.session_state.logged_in = False
        st.session_state.role = 'guest'
        st.session_state.username = ''

    if not st.session_state.logged_in:
        tab1, tab2 = st.sidebar.tabs(["Login", "Register"])

        with tab1:
            username = st.text_input("Username", key="login_user")
            password = st.text_input("Password", type='password', key="login_pwd")
            if st.button("Login"):
                conn = sqlite3.connect(DB_FILE)
                c = conn.cursor()
                c.execute('SELECT password, role, is_active, nickname FROM users WHERE username = ?', (username,))
                data = c.fetchone()
                conn.close()

                if data:
                    if check_hashes(password, data[0]):
                        if data[2] == 1:
                            st.session_state.logged_in = True
                            st.session_state.username = username
                            st.session_state.role = data[1]
                            st.session_state.nickname = data[3]
                            st.success(f"欢迎回来, {data[3]}")
                            st.rerun()
                        else:
                            st.error("账号等待管理员审核中。")
                    else:
                        st.error("密码错误")
                else:
                    st.error("用户不存在")

        with tab2:
            new_user = st.text_input("New Username", key="reg_user")
            new_pwd = st.text_input("New Password", type='password', key="reg_pwd")
            new_nick = st.text_input("Nickname", key="reg_nick")

            if st.button("Register Application"):
                conn = sqlite3.connect(DB_FILE)
                c = conn.cursor()
                c.execute('SELECT username FROM users WHERE username = ?', (new_user,))
                if c.fetchone():
                    st.error("用户名已存在")
                else:
                    c.execute('INSERT INTO users (username, password, nickname, role, is_active) VALUES (?, ?, ?, ?, ?)',
                              (new_user, make_hash(new_pwd), new_nick, 'user', 0)) # 默认 is_active = 0
                    conn.commit()
                    st.success("注册申请已提交，请联系管理员审核。")
                conn.close()

    else:
        # 已登录状态
        avatar_bytes = get_avatar(st.session_state.username)
        if avatar_bytes:
            st.sidebar.image(avatar_bytes, width=100, caption=st.session_state.nickname)
        else:
            st.sidebar.markdown(f"**👤 {st.session_state.nickname}**")

        st.sidebar.markdown(f"Role: `{st.session_state.role}`")

        # 用户设置 (修改头像/密码)
        with st.sidebar.expander("Settings"):
            new_avatar = st.file_uploader("Upload Avatar", type=['png', 'jpg'])
            if new_avatar:
                if st.button("Update Avatar"):
                    img_bytes = save_image_to_bytes(new_avatar)
                    conn = sqlite3.connect(DB_FILE)
                    c = conn.cursor()
                    c.execute("UPDATE users SET avatar=? WHERE username=?", (img_bytes, st.session_state.username))
                    conn.commit()
                    conn.close()
                    st.success("头像已更新")
                    st.rerun()

        if st.sidebar.button("Logout"):
            st.session_state.logged_in = False
            st.session_state.role = 'guest'
            st.session_state.username = ''
            st.rerun()

    # --- 管理员面板 (仅管理员可见) ---
    if st.session_state.logged_in and st.session_state.role == 'admin':
        st.sidebar.markdown("---")
        st.sidebar.subheader("🛠 Admin Panel")

        # 用户审批
        with st.sidebar.expander("User Approval"):
            conn = sqlite3.connect(DB_FILE)
            c = conn.cursor()
            c.execute("SELECT username, nickname FROM users WHERE is_active=0")
            pending_users = c.fetchall()

            if not pending_users:
                st.info("没有待审核用户")
            else:
                for u in pending_users:
                    col1, col2 = st.columns([2,1])
                    col1.text(f"{u[1]} ({u[0]})")
                    if col2.button("Approve", key=f"app_{u[0]}"):
                        c.execute("UPDATE users SET is_active=1 WHERE username=?", (u[0],))
                        conn.commit()
                        st.success(f"已通过 {u[0]}")
                        st.rerun()
            conn.close()

        # 内容发布入口
        if st.sidebar.checkbox("Show Publisher Tool"):
            st.sidebar.info("请在主页面上方查看发布工具")

# --- 内容板块 ---

def render_introduce():
    st.title("👋 Introduce")

    col1, col2 = st.columns([1, 2])
    with col1:
        # 放置一张默认的站长图片或Logo
        st.markdown(
            """
            <div style="background-color:#333; height:300px; width:100%; border-radius:10px; display:flex; align-items:center; justify-content:center;">
                <h3 style="color:#666;">Profile Image</h3>
            </div>
            """, unsafe_allow_html=True
        )

    with col2:
        st.markdown("""
        ### 关于我

        欢迎来到我的数字花园。这是一个极简主义的空间，用于记录生活、思考和创作。

        我热衷于：
        * 💻 **Code**: 构建有用的工具。
        * 🖋️ **Writing**: 记录瞬时的灵感。
        * 🎨 **Art**: 捕捉世界的美。

        这个网站采用了 Notion 的设计哲学：**内容至上，形式简约**。
        """)

    st.markdown("---")
    st.markdown("#### Timeline")
    st.info("2025 - 建立了这个 Streamlit 博客")
    st.info("2023 - 开始专注于 Web 开发与 AI 交互")

def render_content_feed(category):
    st.title(f"📂 {category}")

    # --- 管理员发布区域 ---
    if st.session_state.get('logged_in') and st.session_state.role == 'admin':
        with st.expander(f"➕ New {category} Post", expanded=False):
            with st.form(f"new_{category}_form"):
                new_title = st.text_input("Title")
                new_content = st.text_area("Content (Markdown supported)", height=150)
                uploaded_img = st.file_uploader("Cover Image (Optional)", type=['png', 'jpg', 'jpeg'])
                submit = st.form_submit_button("Publish")

                if submit and new_title and new_content:
                    img_data = save_image_to_bytes(uploaded_img)
                    conn = sqlite3.connect(DB_FILE)
                    c = conn.cursor()
                    c.execute("INSERT INTO posts (category, title, content, image) VALUES (?, ?, ?, ?)",
                              (category, new_title, new_content, img_data))
                    conn.commit()
                    conn.close()
                    st.success("发布成功！")
                    st.rerun()

    # --- 内容展示 ---
    conn = sqlite3.connect(DB_FILE)
    c = conn.cursor()
    c.execute("SELECT id, title, content, created_at, image FROM posts WHERE category=? ORDER BY created_at DESC", (category,))
    posts = c.fetchall()
    conn.close()

    if not posts:
        st.caption("这里还是一片荒原...")

    for post in posts:
        pid, title, content, date, img_data = post

        # 容器开始
        st.markdown(f'<div class="notion-card">', unsafe_allow_html=True)

        st.subheader(title)
        st.caption(f"📅 {date}")

        if img_data:
            st.image(img_data, use_column_width=True)

        st.markdown(content)

        # 评论区开关
        with st.expander(f"💬 Comments"):
            # 显示已有评论
            conn = sqlite3.connect(DB_FILE)
            c = conn.cursor()
            c.execute("""
                SELECT comments.content, users.nickname, comments.created_at, users.avatar
                FROM comments
                JOIN users ON comments.username = users.username
                WHERE post_id=? ORDER BY created_at DESC
            """, (pid,))
            comments = c.fetchall()
            conn.close()

            for cmt in comments:
                c_content, c_nick, c_date, c_avatar = cmt
                # 简单渲染评论
                st.markdown(
                    f"""
                    <div class="comment-box">
                        <strong>{c_nick}</strong> <span style="color:#888; font-size:0.8em;">{c_date}</span><br>
                        {c_content}
                    </div>
                    """, unsafe_allow_html=True
                )

            # 发布评论 (仅登录用户)
            if st.session_state.get('logged_in'):
                comment_txt = st.text_input("Write a comment...", key=f"cmt_in_{pid}")
                if st.button("Send", key=f"btn_cmt_{pid}"):
                    if comment_txt:
                        conn = sqlite3.connect(DB_FILE)
                        c = conn.cursor()
                        c.execute("INSERT INTO comments (post_id, username, content) VALUES (?, ?, ?)",
                                  (pid, st.session_state.username, comment_txt))
                        conn.commit()
                        conn.close()
                        st.rerun()
            else:
                st.caption("登录后可发表评论")

        st.markdown('</div>', unsafe_allow_html=True) # 容器结束

def render_gallery():
    st.title("🎨 Gallery")

    # --- 管理员上传图片 ---
    if st.session_state.get('logged_in') and st.session_state.role == 'admin':
        with st.expander("➕ Upload Art", expanded=False):
            with st.form("gallery_upload"):
                title = st.text_input("Title")
                desc = st.text_area("Description")
                art_file = st.file_uploader("Image File", type=['png', 'jpg', 'jpeg'])
                submit = st.form_submit_button("Upload to Gallery")

                if submit and art_file:
                    img_data = save_image_to_bytes(art_file)
                    conn = sqlite3.connect(DB_FILE)
                    c = conn.cursor()
                    c.execute("INSERT INTO posts (category, title, content, image) VALUES (?, ?, ?, ?)",
                              ('Gallery', title, desc, img_data))
                    conn.commit()
                    conn.close()
                    st.success("上传成功")
                    st.rerun()

    # --- 瀑布流/网格展示 ---
    conn = sqlite3.connect(DB_FILE)
    c = conn.cursor()
    c.execute("SELECT id, title, content, image FROM posts WHERE category='Gallery' ORDER BY created_at DESC")
    items = c.fetchall()
    conn.close()

    if items:
        # 使用列布局模拟网格
        cols = st.columns(3)
        for idx, item in enumerate(items):
            pid, title, content, img_data = item
            with cols[idx % 3]:
                if img_data:
                    st.image(img_data, use_column_width=True)
                st.caption(f"**{title}**")
                if content:
                    st.caption(content)
                st.markdown("---")
    else:
        st.caption("画廊暂时没有展品。")

# --- 主程序逻辑 ---

def main():
    # 初始化侧边栏用户系统
    sidebar_user_system()

    # 侧边栏导航
    st.sidebar.title("Navigation")
    menu = st.sidebar.radio("Go to", ["Introduce", "Blogs", "Writing", "Gallery"])

    st.sidebar.markdown("---")
    st.sidebar.markdown("© 2025 My Personal Space")

    # 页面路由
    if menu == "Introduce":
        render_introduce()
    elif menu == "Blogs":
        render_content_feed("Blogs")
    elif menu == "Writing":
        render_content_feed("Writing")
    elif menu == "Gallery":
        render_gallery()

if __name__ == "__main__":
    main()
